// @govcore/content/compile — the definition → DDL compiler (Rule 1).
//
// The defining choice of the engine (Appendix B, Rule 1): a content type is
// compiled into a REAL table + migration — real columns, types, indexes, FKs,
// org scope, and the same Row-Level Security as a hand-written platform table —
// never an EAV blob. The emitted SQL joins the migration stream and is applied
// by govcore-migrate, so the audited/versioned schema story and RLS (§13.1)
// apply to engine tables exactly as to hand-written ones.

import { isScalarField, type ContentTypeDefinition, type ScalarFieldType } from './types'
import { WORKFLOW_STATUSES, DEFAULT_WORKFLOW_STATUS } from './workflow'

/** Schema that generated content tables live in (kept apart from `govcore`). */
export const DEFAULT_CONTENT_SCHEMA = 'content'

export interface CompileOptions {
  /** Postgres schema for the generated table. Defaults to `content`. */
  schema?: string
}

export interface CompiledContentType {
  schema: string
  tableName: string
  /** The full migration DDL: table + index + RLS. Idempotent (IF NOT EXISTS). */
  sql: string
}

/** Postgres column type for each scalar field type. */
const PG_TYPE: Record<ScalarFieldType, string> = {
  text: 'text',
  textarea: 'text',
  number: 'numeric',
  boolean: 'boolean',
  date: 'date',
}

/**
 * Compile a content-type definition into idempotent migration DDL: a table in
 * the content schema with `id`, `organization_id` (FK → govcore.organizations),
 * the declared columns, a `status` lifecycle column, timestamps, an org index,
 * and ENABLE/FORCE RLS with the `app.current_org` GUC policy (matching
 * 0001_platform_security.sql). Throws on a relationship field type (Rule 2).
 */
export function compileContentType(
  def: ContentTypeDefinition,
  opts: CompileOptions = {},
): CompiledContentType {
  const schema = opts.schema ?? DEFAULT_CONTENT_SCHEMA
  const t = `${schema}.${def.name}`

  const columns: string[] = [
    '  id uuid PRIMARY KEY DEFAULT gen_random_uuid()',
    '  organization_id uuid NOT NULL REFERENCES govcore.organizations (id) ON DELETE CASCADE',
  ]
  for (const f of def.fields) {
    if (!isScalarField(f)) {
      throw new Error(
        `compileContentType("${def.name}"): field "${f.name}" type "${f.type}" is a relationship — not supported yet (Rule 2)`,
      )
    }
    columns.push(`  ${f.name} ${PG_TYPE[f.type]}${f.required ? ' NOT NULL' : ''}`)
  }
  const statusList = WORKFLOW_STATUSES.map((s) => `'${s}'`).join(', ')
  columns.push(`  status text NOT NULL DEFAULT '${DEFAULT_WORKFLOW_STATUS}'`)
  columns.push('  created_at timestamptz NOT NULL DEFAULT now()')
  columns.push('  updated_at timestamptz NOT NULL DEFAULT now()')
  columns.push(`  CONSTRAINT ${def.name}_status_check CHECK (status IN (${statusList}))`)

  const guc = `nullif(current_setting('app.current_org', true), '')::uuid`

  const sql = `-- Generated by @govcore/content from content type "${def.name}".
CREATE SCHEMA IF NOT EXISTS ${schema};

CREATE TABLE IF NOT EXISTS ${t} (
${columns.join(',\n')}
);

CREATE INDEX IF NOT EXISTS ${def.name}_organization_id_idx ON ${t} (organization_id);

-- Tenant isolation by the active-org GUC, FORCEd for the non-owner runtime role.
ALTER TABLE ${t} ENABLE ROW LEVEL SECURITY;
ALTER TABLE ${t} FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS ${def.name}_org_isolation ON ${t};
CREATE POLICY ${def.name}_org_isolation ON ${t}
  USING (organization_id = ${guc})
  WITH CHECK (organization_id = ${guc});
`

  return { schema, tableName: def.name, sql }
}
