import { redirect } from 'next/navigation'
import { revalidatePath } from 'next/cache'
import { auth } from '@/lib/auth'
import { note } from '@/content/note'
import { noteActions } from '@/content/note-actions'
import { ContentForm, ContentListScreen } from '@govcore/content/screens'

export const dynamic = 'force-dynamic'

// A server action wrapping the generated `create` — org scoping, RLS, audit, and
// the `content:write` permission check all come from the tenantAction wrapper.
async function createNote(formData: FormData) {
  'use server'
  await noteActions.create({
    title: String(formData.get('title') ?? ''),
    body: String(formData.get('body') ?? ''),
  })
  revalidatePath('/notes')
}

export default async function NotesPage() {
  const session = await auth()
  if (!session?.user) redirect('/login')

  // RLS-scoped to the active org by the tenantAction GUC — no org filter here.
  const rows = (await noteActions.list()) as Record<string, unknown>[]

  return (
    <main className="mx-auto max-w-4xl px-6 py-10">
      <ContentListScreen
        def={note}
        rows={rows}
        basePath="/notes"
        title="Notes"
        description="Defined as data — the table, RLS, validation, CRUD actions, and these screens are all generated by @govcore/content."
      />

      <section className="mt-10">
        <h2 className="mb-3 text-lg font-semibold">New note</h2>
        <ContentForm def={note} action={createNote} />
      </section>
    </main>
  )
}
